export default {
  // back_Screen: require('../assets/images/back_image.png'),
  Shout_Out: require('../assets/images/Shout_Out.png'),
  // bg:require('../assets/images/bg.png'),
  Button_back:require('../assets/images/Button_back.png'),
  back_image: require('../assets/images/back_image.png'),
  boy_one: require('../assets/images/boy_one.png'),
  girl_one: require('../assets/images/girl_one.png'),
  Setting: require('../assets/images/Setting.png'),
  searce: require('../assets/images/searce.png'),
  EricaBrewster:require('../assets/images/EricaBrewster.png'),
  Group_1:require('../assets/images/Group_1.png'),
  AnnieLawson:require('../assets/images/AnnieLawson.png'),
  DaisyCronk:require('../assets/images/DaisyCronk.png'),
  MadelineBlomfield:require('../assets/images/MadelineBlomfield.png'),
  MadelineKohler:require('../assets/images/MadelineKohler.png'),
  MayaFlood:require('../assets/images/MayaFlood.png'),
  LaylaBrockman:require('../assets/images/LaylaBrockman.png'),
  KeiraLindesay:require('../assets/images/KeiraLindesay.png'),
  LeahSchlapp:require('../assets/images/LeahSchlapp.png'),
  Mask_searce:require('../assets/images/Mask _searce.png'),
  Group_3number:require('../assets/images/Group_3number.png'),
  Group_2number:require('../assets/images/Group_2number.png'),
  scrollbtn:require('../assets/images/scrollbtn.png'),
  Arrow_left:require('../assets/images/Arrow_left.png'),
  seactrcbar_1:require('../assets/images/seactrcbar_1.png'),
  settingbar:require('../assets/images/settingbar.png'),
  system:require('../assets/images/system.png'),
  Male:require('../assets/images/Male.png'),
  Couple:require('../assets/images/Couple.png'),
  Rectangle:require('../assets/images/Rectangle.png'),
  baby:require('../assets/images/baby.png'),
  FemaleAll:require('../assets/images/FemaleAll.png'),
  Rectanglewhite:require('../assets/images/Rectanglewhite.png'),
  Gola:require('../assets/images/Gola.png'),
  Rectangledark:require('../assets/images/Rectangledark.png'),
  threedout:require('../assets/images/threedout.png'),
  logoman:require('../assets/images/logoman.png'),
  prethvi:require('../assets/images/prethvi.png'),
  bag:require('../assets/images/bag.png'),
  camera:require('../assets/images/camera.png'),
  speaker:require('../assets/images/speaker.png'),
  bluegola:require('../assets/images/bluegola.png'),
  url:require('../assets/images/url.png'),
  watch:require('../assets/images/watch.png'),
  rachel:require('../assets/images/rachel.png'),
  Rectangle_mesej:require('../assets/images/Rectangle_mesej.png'),
  Report:require('../assets/images/Report.png'),
  Rectangle_10:require('../assets/images/Rectangle_10.png'),
  Rectangle_131:require('../assets/images/Rectangle_131.png'),
  Rectangle_130:require('../assets/images/Rectangle_130.png'),
  video:require('../assets/images/video.png'),
  videosong:require('../assets/images/videosong.png'),
  Rectangle_134:require('../assets/images/Rectangle_134.png'),
  xyz:require('../assets/images/xyz.png'),
  Group_688:require('../assets/images/Group_688.png'),
  Group_708:require('../assets/images/Group_708.png'),
  Group_600:require('../assets/images/Group_600.png'),
  Mask_circle:require('../assets/images/Mask_circle.png'),
  block:require('../assets/images/block.png'),
  unfriend:require('../assets/images/unfriend.png'),
  vinson:require('../assets/images/vinson.png'),
  profile:require('../assets/images/profile.png'),
  terms:require('../assets/images/terms.png'),
  privacy:require('../assets/images/privacy.png'),
  logout:require('../assets/images/logout.png'),
  lock:require('../assets/images/lock.png'),
  bda:require('../assets/images/bda.png'),
  scanner:require('../assets/images/scanner.png'),
  Rectangle_nc:require('../assets/images/Rectangle_nc.png'),
  Group_172:require('../assets/images/Group_172.png'),
  Mask_group:require('../assets/images/Mask_group.png'),
  Vector:require('../assets/images/Vector.png'),
  Rectangle_132:require('../assets/images/Rectangle_132.png'),
  videoS:require('../assets/images/videoS.png'),
  blockr:require('../assets/images/blockr.png'),
  unfriend_xyz:require('../assets/images/unfriend_xyz.png'),
  jdb:require('../assets/images/jdb.png'),
  india:require('../assets/images/india.png'),
  endchate:require('../assets/images/endchate.png'),

};
